### ISSUE TITLE
bitcoinaverage pro plan needed?

### ISSUE THREAD

**Issue by rraallvv** [kodaxx/DashRates-API#5]
I'm getting this error on the console output:

```
BTC/DASH: Error: Request failed with status code 403
```

Do I need a pro plan on bitcoinaverage for this API to work? If so, have you considered to use coingecko instead, which is free?

Keep up the good work.

**Comment by rraallvv** [comment]
These two API endpoints will get you covered using Coingecko

```
https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=usd,cad
{"bitcoin":{"usd":6786.92,"cad":9449.95}}
```

```
https://api.coingecko.com/api/v3/simple/price?ids=dash&vs_currencies=btc
{"dash":{"btc":0.01069771}}
```

**Comment by kodaxx** [comment]
Thanks! I have one more solution as well, I'll worked to get it implemented - but if you make a PR, I'll likely approve

**Comment by rraallvv** [comment]
@kodaxx , here you go!

**Comment by kodaxx** [comment]
Awesome! Sent you a Brave tip (if you use Brave)

**Comment by rraallvv** [comment]
@kodaxx 

Oh wow! Thanks.

I just created a Brave Publisher account and finished verifying my GitHub account. It says that my verified status will be displayed in the Brave browser within the next 24-48 hours.

Also, it seems the dash.casa website is down, so the price for VES is showing an error. I think I can replace it with LocalBitcoin's, do you want me to send a PR? No need to tip for that one, although I'm glad you did, becouse it gave me the opportunity to try out the platform 😉

**Comment by kodaxx** [comment]
Yes! Please send a PR if you can, and more tips to come :)

**Comment by rraallvv** [comment]
[Here](https://github.com/kodaxx/DashRates-API/pull/10) is the PR to fix VES rate, also made a little refactoring to replace the "BitcoinAverage" text with "Coingecko" in the variable names and the cache reference

**Comment by rraallvv** [comment]
Sorry to make [this](https://github.com/kodaxx/DashRates-API/pull/11) change in a separate PR, but it seems the BitcoinAverage was accessible directly from an endpoint in the DashRates-API, I replaced that one with an endpoint for Coingecko too

**Comment by rraallvv** [comment]
I apologize for having done multiple PRs just to fix the VES rate. With a bit more of preparation and testing from my part it would have been just one PR. Hopefully [this one](https://github.com/kodaxx/DashRates-API/pull/12) would be the las PR to have the VES rate fully functional. It turns out the rate from LocalBitcoins (BTC/USD) was missing a multiplier (BTC/DASH rate) to have the actual value.

**Comment by rraallvv** [comment]
@kodaxx I ported Spark to Svelte 3 and changed it, and also DashRates-API, to use the Nimiq blockchain. Since you mentioned about the Brave browser, and Nimiq is a blockchain native to the web, I thought you maybe be interested.

These are the repos:

* Spark Nimiq https://github.com/rraallvv/spark-payments-nimiq-webpack
* NimiqRates-API https://github.com/rraallvv/NimiqRates-API

You can try out Spark Nimiq [here](http://spark-testnet.nimizuela.org), although at the moment it's doing the verifications only on the Testnet.

The Nimiq web wallet is here http://safe.nimiq.com, and the Testnet wallet here http://safe.nimiq-testnet.com

**Comment by kodaxx** [comment]
That's awesome! I've been interested in svelte, looks similar to Vue. Will
look into it - great job 👏

**Comment by rraallvv** [comment]
I was trying to find an excuse to play a bit with Svelte, and then I found spaceavocado's template with a router that is more or less the same as the oficial Vue router, so I decided to give it a try. It's pretty cool the approach of a disappearing framework with a compiler instead of doing everything at rune time.

**Comment by kodaxx** [comment]
Do you have discord or keybase at all?

**Comment by rraallvv** [comment]
I'm on Discord my username is rraallvv#7360
